### ISSUE TITLE
@ToDo List

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#7]
- [x] : Modifier la page d'accueil, @Maxouhell @rtrompier
- [x] : Modifier le theme de prismJS (default ou coy) dans les composants CodeViewer et Markdown @Maxouhell 
- [x] : Séparer exemple input du deja-date-time-selector (dans différents mdCard) @Maxouhell @rtrompier
- [x] : Séparer dans différent mdCard Accordion Default et Secondary ~~@anaislabarre~~ @rtrompier
- [x] : Séparer tous les exemples (mettre un header de panel) ~~@guerricm, @dejajs~~ @rtrompier
- [x] : Fixer la scrollBar dans le content du Tabs dans l'exemple Monaco
- [x] : Fixer la position des SnackBar
- [x] : Fixer la position du menu (menu caché) dans l'exemple Menu
- [x] : Fixer le readme du treelist (manque certainement un TD)
- [x] : Fixer le readme de la datagrid (manque certainement un TD)
- [x] : Theming (md-palette) @Maxouhell @rtrompier
- [x] : DateRangePicker @Maxouhell 
- [x] : DateTimeRangePicker @Maxouhell 
- [x] : TimePicker @Maxouhell 
- [x] : add mask to DatePicker @Maxouhell 
- [x] : Grid on push @vapkse 
- [x] : Doc ViewPort @vapkse 
- [x] :  Issue scrolling ViewPort @vapkse 
- [x] : TreeList variable rowHeight (viewPort) @vapkse 
- [ ] : Supprimer les parties "Examples" dans les fichier readme
- [ ] : Pour chaque demo de composant, créer un tab overview avec un exemple simple du composant (keng), 
- [ ] : Bien expliquer dans le overview les fonctionnalités dans la data-grid (gestion d'un view port, renderer des cellules, grouping, ...) @vapkse
- [ ] : Traduction en anglais @fischerflorian 
- [ ] : Test End-to-End @rtrompier 
- [x] : Meilleur demo pour Treelist @vapkse
- [x] : Meilleur demo pour Select @vapkse
- [x] : Meilleur demo pour Grid @vapkse
- [x] : ViewPort EnsureVisible @vapkse
- [x] : Selecteur plus sexy pour les themes @Maxouhell 
- [x] : Stocker les themes dans le local storage @Maxouhell
